"""
Generate docs/COMPLIANCE_MATRIX.md from ``[RULE: ...]`` tags in the code.

Usage::

    python scripts/compliance_report.py          # write the matrix
    python scripts/compliance_report.py --check  # exit 1 if the file is stale (CI)

[RULE: GDPR-ART5-2]  Accountability: auditors get a live, generated mapping of
                     each requirement to the exact lines that implement it.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from finrag.compliance import RULES  # noqa: E402

TAG = re.compile(r"\[RULE:\s*([A-Z0-9-]+)\]")
OUTPUT = ROOT / "docs" / "COMPLIANCE_MATRIX.md"


def collect() -> dict[str, list[str]]:
    """Map rule id -> sorted list of 'path:line' locations."""
    found: dict[str, list[str]] = defaultdict(list)
    for path in sorted((ROOT / "finrag").rglob("*.py")):
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            for rule in TAG.findall(line):
                found[rule].append(f"{path.relative_to(ROOT).as_posix()}:{lineno}")
    return found


def render(found: dict[str, list[str]]) -> str:
    """Render the Markdown matrix grouped by framework."""
    lines = [
        "# Compliance Matrix",
        "",
        "> Generated by `python scripts/compliance_report.py` from `[RULE: ...]` tags in "
        "the source code. Do not edit by hand.",
        "",
        "Each row links a requirement to every place in the code that implements it. "
        "Open the file at the given line to see the control and its explanatory comment.",
        "",
    ]
    by_framework: dict[str, list[str]] = defaultdict(list)
    for rule_id, rule in RULES.items():
        by_framework[rule.framework].append(rule_id)
    for framework, ids in by_framework.items():
        lines += [f"## {framework}", "", "| Rule | Requirement | Implemented at |",
                  "|---|---|---|"]
        for rule_id in ids:
            rule = RULES[rule_id]
            locs = found.get(rule_id, [])
            where = "<br>".join(f"`{loc}`" for loc in locs) or "**NOT IMPLEMENTED**"
            lines.append(f"| `{rule_id}` | **{rule.title}** - {rule.summary} | {where} |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if matrix is stale")
    args = parser.parse_args()
    content = render(collect())
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print("docs/COMPLIANCE_MATRIX.md is stale; regenerate it.", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
